server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_application
    username: root
    password: root@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
